/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'GetNodeDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ExpandNode': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ChatAPI': ApiRouteHandler<{ question: string; context?: Record<string, unknown> }, ApiResponse<200, { answer: string; graph: Record<string, unknown>; clusters: Array<unknown> }>, never>
  }
    
}