/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'GetNodeDetails': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; name: string; description: string; type: string; clusterId: string; references: Array<Record<string, unknown>>; relatedNodes: Array<Record<string, unknown>> }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'ExpandNode': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { newNodes: Array<unknown>; newEdges: Array<unknown> }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'ChatAPI': ApiRouteHandler<{ question: string; context?: Record<string, unknown> }, ApiResponse<200, { answer: string; graph: Record<string, unknown>; clusters: Array<unknown> }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, never>
  }
    
}